### PR TITLE
Convert to python3 using 2to3

### LINKED ISSUE #23: ASCII codec can't deal with accents
I have a wrong name to use with jipdate, it seems:
```
$ ./jipdate.py -q
Password: 
Traceback (most recent call last):
  File "./jipdate.py", line 458, in <module>
    main(sys.argv)
  File "./jipdate.py", line 442, in main
    filename = get_jira_issues(jira, username)
  File "./jipdate.py", line 213, in get_jira_issues
    f.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 62: ordinal not in range(128)
```
Issue might lie in my last name: Díaz. It can also be any other thing, though, as I do have a tendency to throw in some accents left and right in my cards.

### PR DESCRIPTION
**Pull request by danrue**
Fixes #23

Signed-off-by: Dan Rue <dan.rue@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
I didn't test very many use-cases - just 'jipdate -q --dry-run', and mrchapp confirmed that it fixes #23.

**Comment by jbech-linaro** [comment]
Thanks for the patch Dan. I gave it a try. First the README.md also needs an update, since there we are saying that jipdate is a Python2 thing only. Having that said, after pip3 install the packages and running it I get:
```bash
$ ./jipdate.py -q -t 
Traceback (most recent call last):
  File "./jipdate.py", line 16, in <module>
    import jiralogin
  File "/home/jbech/devel/jipdate/jiralogin.py", line 107
    except JIRAError, e:

SyntaxError: invalid syntax
```
This is fixed by
```patch
diff --git a/jiralogin.py b/jiralogin.py
index de429cf..1165b7a 100644
--- a/jiralogin.py
+++ b/jiralogin.py
@@ -104,7 +104,7 @@ def get_jira_instance(use_test_server):
 
     try:
         j = JIRA(cfg.server, basic_auth=credentials), username
-    except JIRAError, e:
+    except (JIRAError, e):
         if e.text.find('CAPTCHA_CHALLENGE') != -1:
             eprint('Captcha verification has been triggered by '\
                    'JIRA - please go to JIRA using your web '\
```

With that patch applied I get the next issue:
```bash
$ ./jipdate.py -q -t 
Password: 
Traceback (most recent call last):
  File "./jipdate.py", line 458, in <module>
    main(sys.argv)
  File "./jipdate.py", line 442, in main
    filename = get_jira_issues(jira, username)
  File "./jipdate.py", line 211, in get_jira_issues
    f.write(subject)
  File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

So it seems like there are more Python2 to Python3 things not ready yet, so I don't think I can merge this as it is right now, the patch needs a bit more tweaking and testing.

What Python3 version are you using? (On this particular machine I'm running `3.5.3`).

**Comment by jbech-linaro** [comment]
@danrue , my bad, I applied that patch on an older commit, it seems to work fine on latest. I'll merge and create a separate patch for the README.md.

**Comment by jbech-linaro** [comment]
Manually merged the patches/pull request, closing this ticket. Thanks again for the patch!

**Pull request closed without merging**
