### PR TITLE
Resolution

### PR DESCRIPTION
**Pull request by ndechesne**
hi Joakim,

let me know what you think about this change.. I've tested a bit and it seems to be working fine for me.. 

nico

### CODE REVIEW

**Comment by ndechesne** [comment]
@jbech-linaro ping!

**Comment by jbech-linaro** [comment]
Sorry for the delay Nico. First, nice performance improvement with this, really noticeable.

However, "8bea136 jipdate: add support for setting 'resolution' when resolving" introduce a regression.

You should be able to reproduce by using my "username" (and the test server!). Notice two comments and one state change. I believe it's the state change that fails. Before your commits here that same seems to be working.

```bash
$ ./jipdate.py -q -t -u joakim.bech

...
Subject: [Weekly] Week ending 2020-04-06

Hi,

This is the status update from me for the last week.

Cheers!


Joakim Bech

[SWG-377]
# Header: Riscure report 2019-06-19
# Type: Epic
# Status: In Progress
# No updates since last week.
test

[SWG-375]
# Header: OP-TEE tax based cycle work
# Type: Initiative
# Status: In Progress
# No updates since last week.
test

[SWG-330]
# Header: AOSP Keymaster 3 initiative
# Type: Initiative
Status: Open
# No updates since last week.

[SWG-318]
# Header: Support building OP-TEE with clang
# Type: Epic
# Status: In Progress
# No updates since last week.

[SCMI-1]
# Header: SCMI on secure side on Armv7-A
# Type: Initiative
# Status: In Progress
# No updates since last week.

[LPE-11]
# Header: TPM in TEE
# Type: Initiative
# Status: In Progress
# No updates since last week.

...

These JIRA cards will be updated as follows:

Traceback (most recent call last):
  File "./jipdate.py", line 522, in <module>
    main(sys.argv)
  File "./jipdate.py", line 519, in main
    parse_status_file(jira, filename)
  File "./jipdate.py", line 393, in parse_status_file
    {'transition': transition_id, 'resolution': resolution_id}))
UnboundLocalError: local variable 'resolution_id' referenced before assignment

```
Otherwise things seems to be working, so if you can resolve that one, then I can push this and what you have in #34.

**Comment by ndechesne** [comment]
ouch.. sorry, actually no, it's the comment without a state change that doesn't work.. i should have tried that ;) will fix shortly.

**Comment by ndechesne** [comment]
it should be fixed now!

**Comment by jbech-linaro** [comment]
Yes, problem solved, thanks!

**Pull request merged**
