### PR TITLE
jipstatus: Update the URL to new server

### PR DESCRIPTION
**Pull request by vinodkoul**
projects.linaro.org is no longer in use, so update the link to new
server for jipstatus.

Signed-off-by: Vinod Koul <vkoul@kernel.org>

### CODE REVIEW

**Comment by vinodkoul** [comment]
@ndechesne @jbech-linaro Does this look good..?

**Comment by ndechesne** [comment]
i think i found a better way.. let me push a PR

**Comment by ndechesne** [comment]
I would recommend https://github.com/Linaro/jipdate/pull/46 instead of this one.

**Comment by vinodkoul** [comment]
> I would recommend #46 instead of this one.

Ack, that is a better approach, so closing this

**Pull request closed without merging**
