### PR TITLE
jipdate: fix regression with file operation

### LINKED ISSUE #35: Jipdate fails after April 7th changes
TCWG CI uses jipdate master branch to add comments to jira about regressions detected in various components.  Jipdate started to fail this morning with:
`UnboundLocalError: local variable 'issues' referenced before assignment`
Full log is at https://ci.linaro.org/view/tcwg_kernel-gnu/job/tcwg_kernel-bisect-llvm-master-arm-next-allmodconfig/73/console .

The problem occurred between April 3 and April 8, this range only has 4 commits from @ndechesne .
@ndechesne , would you please investigate?

To reproduce the problem this should be enough:
```
cat > jira-body.txt <<EOF
[GNU-587]
Test comment
EOF
export JIRA_USERNAME=$USER
export JIRA_PASSWORD=$PASSWORD
export EDITOR=cat
echo y | jipdate.py -f jira-body.txt
```

### PR DESCRIPTION
**Pull request by ndechesne**
A regression was found in
49866d0 jipdate: avoid refetching issues during the parsing of the text file

This patch introduced an optimization when using a user query
(-q). However when using file mode, we don't run a Jira query in the
initial phase, so once we do the parsing, the issues have not been
fetched yet.

This patch fixes this situation, so now we do the following:

1. we check if we have fetched issues already
2. if so, we check if the issue we are looking for exist in the
already fetched set
3. otherwise, we query Jira

Fixes #35.

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>

### CODE REVIEW

**Comment by maxim-kuvyrkov** [comment]
Still doesn't work, but for a different reason.  Now it says
```
03:17:45.688 These JIRA cards will be updated as follows:
03:17:45.688 
03:17:45.688 
03:17:45.688 No change, Jira was not updated!
```
and then a new error:
```
03:17:45.688 Exception ignored in: <bound method Magic.__del__ of <magic.Magic object at 0x7fedafa624a8>>
03:17:45.688 Traceback (most recent call last):
03:17:45.688   File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
03:17:45.688     if self.cookie and magic_close:
03:17:45.688 AttributeError: 'Magic' object has no attribute 'cookie'
```
Full log at https://ci.linaro.org/job/tcwg_kernel-bisect-gnu-master-arm-next-allmodconfig/90/console .

**Comment by maxim-kuvyrkov** [comment]
TCWG processes rely on Jira receiving these messages, so, @ndechesne , would you please revert for now, and I'll help you test this offline?

**Comment by ndechesne** [comment]
https://github.com/Linaro/jipdate/pull/37

But i have the feeling that it's a different issue this time.. 

Can you please share your text file and use case? For me both -q and -f work file, using the test server.

**Comment by maxim-kuvyrkov** [comment]
You're right.  Something else is going on.
With #36 adding comments to jira as myself works (JIRA_USERNAME=maxim.kuvyrkov@linaro.org).
However, adding comments as tcwg-jira automation user has been broken since beginning of March; the last comment from tcwg-jira is dated February 28th.  This is, likely, a Jira configuration issue, and not Jipdate's.
Please merge #36 and drop #37.
Thanks!

**Comment by jbech-linaro** [comment]
Merged, holding off with #37 closing until beginning of next week, thanks! Have a good weekend!

**Pull request merged**
